version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    networks:
      - app_network
    command: /bin/sh -c "until nc -z -v -w30 rabbitmq 5672; do echo 'Waiting for RabbitMQ...'; sleep 5; done; php artisan queue:work --queue=rabbitmq"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

networks:
  app_network:
